### ISSUE TITLE
FQMS Aggressiveness doesn't work

### ISSUE THREAD

**Issue by vPumpking** [Relintai/mesh_utils#2]
Hello, I'm working on a project where I need a model LOD setting. I'm using your mesh_utils module like this in an autoload script:
```gdscript
extends Node

# Export variables for easy configuration in the inspector
@export var target_vertex_count: int = 1000
@export var aggressiveness: float
@export var verbose: bool = false

# Function to simplify a mesh instance
func simplify_mesh_instance(mesh_instance: MeshInstance3D):
    if not mesh_instance or not mesh_instance.mesh or not mesh_instance.mesh is ArrayMesh:
        return

    var original_mesh: ArrayMesh = mesh_instance.mesh
    var simplified_mesh = ArrayMesh.new()

    var surface_count = original_mesh.get_surface_count()
    var simplifier = FastQuadraticMeshSimplifier.new()

    for i in range(surface_count):
        var surface_arrays = original_mesh.surface_get_arrays(i)
        if surface_arrays.is_empty():
            continue

        # Preserve the material
        var material = original_mesh.surface_get_material(i)

        simplifier.initialize(surface_arrays)
        var current_vertex_count = surface_arrays[ArrayMesh.ARRAY_VERTEX].size()

        # Simplify only if the current vertex count is greater than the target
        if current_vertex_count > target_vertex_count:
            # Ensure the aggressiveness is within a reasonable range
            var effective_aggressiveness = clamp(aggressiveness, 0.0, 10.0)
            simplifier.simplify_mesh(target_vertex_count, effective_aggressiveness, verbose)

        var new_surface_arrays = simplifier.get_arrays()

        if not new_surface_arrays.is_empty():
            # Add surface arrays with proper format and materials
            simplified_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, new_surface_arrays)
            simplified_mesh.surface_set_material(simplified_mesh.get_surface_count() - 1, material)

    # Apply the simplified mesh to the mesh instance
    mesh_instance.mesh = simplified_mesh

# Function to simplify all mesh instances in the scene
func simplify_meshes_in_scene(root_node: Node):
    var mesh_instances = find_mesh_instances(root_node)
    for mesh_instance in mesh_instances:
        simplify_mesh_instance(mesh_instance)

# Helper function to find all MeshInstance3D nodes
func find_mesh_instances(node: Node) -> Array:
    var result = []
    if node is MeshInstance3D:
        result.append(node)
    for child in node.get_children():
        result.append_array(find_mesh_instances(child))
    return result
```
this script is autoloaded as MeshSimplifier and used like this in a scene:
```gdscript
extends Node

# Import the MeshSimplifier autoload
onready var mesh_simplifier := MeshSimplifier

# Export variables for easy configuration in the inspector
@export var target_vertex_count: int = 1000
@export var aggressiveness: float = 0.5

func _ready():
    # Set parameters for simplification
    mesh_simplifier.target_vertex_count = target_vertex_count
    mesh_simplifier.aggressiveness = aggressiveness

    # Simplify all meshes in the scene
    mesh_simplifier.simplify_meshes_in_scene(self)
```
But no matter what the value of aggressiveness is, the compression stays the same, and is too high for what I want.

Can you please help me?

**Comment by vPumpking** [comment]
Also I think that would be a good occasion to make a quick use guide on the mesh_utils readme

**Comment by Relintai** [comment]
Yeah, I forgot about this. If I remember correctly it should work, but it's kind of finicky.

It has some bug(s), but back then I got sidetracked due to other work and forgot about it.

It's also still using std containers internally.

I'll add it to my todo list again.

Also which godot 4 version are you using?

**Comment by Relintai** [comment]
In Godot 4.2.2 ImporterMesh seems to have a generate_lods() method, see:

https://github.com/godotengine/godot/blob/master/scene/resources/3d/importer_mesh.cpp#L272

You should try it, if you haven't already, if it fits your use case you won't have to wait for me to fix this.

**Comment by vPumpking** [comment]
> Yeah, I forgot about this. If I remember correctly it should work, but it's kind of finicky.
> 
> It has some bug(s), but back then I got sidetracked due to other work and forgot about it.
> 
> It's also still using std containers internally.
> 
> I'll add it to my todo list again.
> 
> Also which godot 4 version are you using?

I'm using godot 4.2

**Comment by vPumpking** [comment]
> In Godot 4.2.2 ImporterMesh seems to have a generate_lods() method, see:
> 
> https://github.com/godotengine/godot/blob/master/scene/resources/3d/importer_mesh.cpp#L272
> 
> You should try it, if you haven't already, if it fits your use case you won't have to wait for me to fix this.

it would be useful if it's something different from the autoLOD importer parameter, because
* autoLOD works only on scenes and not on obj
* it's only triggered by the distance to the camera, where I want to have a global decimation for performance

Also one advantage of your one is the models are generated and replaced at runtime, taking way less space on disk

**Comment by vPumpking** [comment]
So with importerMesh, I would clear all the meshes and then generate a lod for them and replace the original mesh with the lod?

**Comment by vPumpking** [comment]
found this, this is a very good start https://github.com/godotengine/godot-proposals/issues/6402

**Comment by vPumpking** [comment]
here it is! I think maybe it could be useful to you https://github.com/vPumpking/MeshLodGenerator/tree/main

**Comment by vPumpking** [comment]
thank you for your help! good luck for your projects
